{"uuid": "01c8c31d-870d-4c1d-9b40-63287259dcab", "children": ["2321861a-9979-470c-9ae1-dcd0f91fcc30"], "befores": [{"name": "_xunit_setup_class_fixture_Test_plugins", "status": "broken", "statusDetails": {"message": "ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。\n", "trace": "  File \"D:\\python 3.8.7\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\python 3.8.7\\lib\\site-packages\\_pytest\\fixtures.py\", line 1130, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\python 3.8.7\\lib\\site-packages\\_pytest\\fixtures.py\", line 902, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\python 3.8.7\\lib\\site-packages\\_pytest\\python.py\", line 864, in xunit_setup_class_fixture\n    _call_with_optional_argument(func, self.obj)\n  File \"D:\\python 3.8.7\\lib\\site-packages\\_pytest\\python.py\", line 785, in _call_with_optional_argument\n    func(arg)\n  File \"d:\\wanwan1\\test_plugins.py\", line 18, in setup_class\n    self.p1.initialize()\n  File \"d:\\wanwan1\\login.py\", line 132, in initialize\n    self.tel_debug_FM104()\n  File \"d:\\wanwan1\\login.py\", line 59, in tel_debug_FM104\n    self.tn.read_until(b\"login: \",timeout=1)\n  File \"D:\\python 3.8.7\\lib\\telnetlib.py\", line 317, in read_until\n    self.fill_rawq()\n  File \"D:\\python 3.8.7\\lib\\telnetlib.py\", line 526, in fill_rawq\n    buf = self.sock.recv(50)\n"}, "start": 1700639028728, "stop": 1700639028748}], "start": 1700639028728, "stop": 1700639028904}